# Run one topology event at update step 200, then stop refining topology.
voxel_size: 0.001
novelty_distance: 0.001

strategy:
  refine_start_iter: 100000
  refine_stop_iter: 100001
  verbose: true

update_strategy:
  refine_start_iter: 100
  refine_stop_iter: 201
